### ISSUE TITLE
Docs module index

### ISSUE THREAD

**Issue by domibarton** [confirm/ansibleci#10]
The current docs have [no module index](http://ansibleci.readthedocs.org/en/latest/py-modindex.html). We should decide what to do:
- Create the module index
- Remove the link from the [index](docs/index.rst).

**Comment by pstauffer** [comment]
maybe we can create a short "about" page as index page like ansible (https://github.com/ansible/ansible/blob/devel/docsite/rst/index.rst). What's your oppinion @domibarton ?

**Comment by domibarton** [comment]
Isn't that the purpose part? Please see issue #9 for docs and enhancements, as this issue is only for the module index.
