### ISSUE TITLE
FEATURE: Test the commits with the Python Style Guide

### ISSUE THREAD

**Issue by pstauffer** [confirm/ansibleci#14]
Ckeck for pep8...

pep8 Configuration for excludes:
http://pep8.readthedocs.org/en/latest/intro.html#configuration

```
[pep8]
ignore = E501,E221
```

Style Guide:
http://ansibleci.readthedocs.org/en/develop/contribution.html#python-style-guide

Github CI:
https://developer.github.com/guides/building-a-ci-server/

**Comment by domibarton** [comment]
Wanna go for Travis?

**Comment by pstauffer** [comment]
Yeah :+1: 

Travis CI:
https://github.com/integrations/travis-ci
https://docs.travis-ci.com/

**Comment by pstauffer** [comment]
I've tried it out with a fork of our project in my own account...

https://github.com/pstauffer/ansibleci
- permit travis-ci access to the github account
- adding .travis.yml
- push it

For testing I've also added the build-status to the readme.

What do you think about that? Shall we integrate it on our confirm account?

**Comment by domibarton** [comment]
Yeah looks great :+1: 
Let's create a feature branch for it.
